# -*- coding: utf-8 -*-
"""ceaser cypher projectipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OPhxJuifuVVr9DJBDEu-VAW4KRIYVunW
"""

alphebet = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']

def caesar(word, shift):
  result = []#empty list to add final result to
  for x in word:#loops for however many letters there are
    try:#must be a letter
      if x in alphebet:#if a letter in the word is in the alphabet
        index = alphebet.index(x)#finds the letter in the alphabet
        shifted_index = (index + shift) % len(alphebet)#makes the shift add onto the index, divides by 26 so if it loops it will work
        result.append(alphebet[shifted_index])#adds the shifted letter to our result list
    #keeps repeating until word is over
    except ValueError:
      result.append(x)
      print('I dont handle numbers')
  return "".join(result)#prints the combined list
#used colab suggestions to help fix syntax errors, spoke about it when I met with you


alphebet = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']

def decoder(word, shift):
  result = []
  for x in word:
    if x in alphebet:
      index = alphebet.index(x)
      shifted_index = (index - shift) % len(alphebet)
      result.append(alphebet[shifted_index])
    else:
      result.append(x)
  return "".join(result)


name=input('welcome to my caesar cypher project, what is your name: ')
print(f'hello {name}')
#mode=input('press 1 to go to the caesar cypher, click 2 to go to the decoder: ')
while True:
  mode=int(input('press 1 to go to the caesar cypher, click 2 to go to the decoder: '))
  if mode == 1:
    word=input('whats your word: ')
    shift=int(input('whats your shift: '))
    print(caesar(word,shift))
    break
  elif mode==2:
    word=input('whats your word: ')
    shift=int(input('how much would you like to decode by: '))
    print(decoder(word,shift))
    break
  else:
    print('thats not an option')